"""Initial migration

Revision ID: 498dcfeac13b
Revises: 
Create Date: 2026-02-08 15:41:22.240775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '498dcfeac13b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_tables',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('hit_policy', sa.Enum('FIRST_HIT', 'COLLECT_ALL', 'UNIQUE', name='hit_policy_enum'), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_tables_slug'), 'decision_tables', ['slug'], unique=True)
    op.create_table('decision_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('logic', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['decision_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_rules_logic', 'decision_rules', ['logic'], unique=False, postgresql_using='gin', postgresql_ops={'logic': 'jsonb_path_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decision_rules_logic', table_name='decision_rules', postgresql_using='gin', postgresql_ops={'logic': 'jsonb_path_ops'})
    op.drop_table('decision_rules')
    op.drop_index(op.f('ix_decision_tables_slug'), table_name='decision_tables')
    op.drop_table('decision_tables')
    # ### end Alembic commands ###
